# Terraform Cloud workspace variables for PR-CYBR-FRONTEND-AGENT
# Values are intentionally redacted; Terraform Cloud injects the real data.
DOCKERHUB_TOKEN                    = "__SET_IN_TFC__"
DOCKERHUB_USERNAME                 = "__SET_IN_TFC__"
GLOBAL_DOMAIN                      = "__SET_IN_TFC__"
GLOBAL_ELASTIC_URI                 = "__SET_IN_TFC__"
GLOBAL_GRAFANA_URI                 = "__SET_IN_TFC__"
GLOBAL_KIBANA_URI                  = "__SET_IN_TFC__"
GLOBAL_PROMETHEUS_URI              = "__SET_IN_TFC__"
GLOBAL_TAILSCALE_AUTHKEY           = "__SET_IN_TFC__"
GLOBAL_TRAEFIK_ACME_EMAIL          = "__SET_IN_TFC__"
GLOBAL_TRAEFIK_ENTRYPOINTS         = "__SET_IN_TFC__"
GLOBAL_ZEROTIER_NETWORK_ID         = "__SET_IN_TFC__"
AGENT_ACTIONS                      = "__SET_IN_TFC__"
AGENT_COLLAB                       = "__SET_IN_TFC__"
NOTION_TOKEN                       = "__SET_IN_TFC__"
NOTION_PAGE_ID                     = "__SET_IN_TFC__"
NOTION_DISCUSSIONS_ARC_DB_ID       = "__SET_IN_TFC__"
NOTION_ISSUES_BACKLOG_DB_ID        = "__SET_IN_TFC__"
NOTION_KNOWLEDGE_FILE_DB_ID        = "__SET_IN_TFC__"
NOTION_PR_BACKLOG_DB_ID            = "__SET_IN_TFC__"
NOTION_PROJECT_BOARD_BACKLOG_DB_ID = "__SET_IN_TFC__"
NOTION_TASK_BACKLOG_DB_ID          = "__SET_IN_TFC__"
