name: Summarize Commits (24h)
description: Build a markdown summary of commits in the last 24 hours
runs:
  using: "composite"
  steps:
    - id: set-window
      shell: bash
      run: |
        since="$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -v-24H +%Y-%m-%dT%H:%M:%SZ)"
        echo "since=$since" >> "$GITHUB_OUTPUT"
    - id: fetch
      uses: actions/github-script@v7
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const since = core.getInput('since') || '${{ steps.set-window.outputs.since }}';
          const commits = await github.rest.repos.listCommits({ owner, repo, since });
          const fmt = c => `- ${c.commit.author.date} — **${c.commit.message.split('\n')[0]}** (${c.sha.slice(0,7)}) by @${c.author?.login || c.commit.author.name}`;
          const body = commits.data.length ? commits.data.map(fmt).join('\n') : "_No commits in the last 24 hours._";
          core.setOutput('body', body);
      with:
        result-encoding: string
    - id: out
      shell: bash
      run: |
        echo "body<<EOF" >> "$GITHUB_OUTPUT"
        echo "${{ steps.fetch.outputs.result }}" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
