name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      tests_passed: ${{ steps.test_result.outputs.tests_passed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull and start containers
        run: docker compose -f .github/workflows/docker-compose.yml up -d

      - name: Capture container ID
        id: container
        run: |
          CONTAINER_ID=$(docker ps -qf "name=pr-cybr-frontend-agent$")
          if [ -z "$CONTAINER_ID" ]; then
            echo "Unable to find running container" >&2
            exit 1
          fi
          echo "container_id=$CONTAINER_ID" >> "$GITHUB_OUTPUT"

      - name: Install dependencies and run tests
        id: run_tests
        continue-on-error: true
        run: |
          CONTAINER_ID="${{ steps.container.outputs.container_id }}"
          docker exec "$CONTAINER_ID" python -m pip install --no-cache-dir -e /workspace
          docker exec "$CONTAINER_ID" python -m unittest discover /workspace/tests

      - name: Record test result
        id: test_result
        run: |
          if [ "${{ steps.run_tests.outcome }}" = "success" ]; then
            echo "tests_passed=true" >> "$GITHUB_OUTPUT"
          else
            echo "tests_passed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Deploy on success
        if: steps.test_result.outputs.tests_passed == 'true'
        run: |
          echo "Tests passed. Deploying..."
          # Add deployment steps here

      - name: Handle failed tests
        if: steps.test_result.outputs.tests_passed != 'true'
        run: |
          echo "Tests failed. Skipping deployment."
          exit 1
