name: delete-old-branches
on:
  schedule:
    - cron: "41 4 * * *"   # daily 04:41 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Prune merged branches older than 14 days
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const protectedNames = new Set(['main','codex']);
            const { data: branches } = await github.rest.repos.listBranches({owner, repo, protected: false, per_page: 100});
            const now = Date.now();
            const olderThan = 14*24*3600*1000;
            for (const b of branches) {
              const name = b.name;
              if (protectedNames.has(name)) continue;
              // skip if default branch
              const repoInfo = await github.rest.repos.get({owner, repo});
              if (name === repoInfo.data.default_branch) continue;

              // has it been merged?
              try {
                const pr = await github.rest.pulls.list({
                  owner, repo, state: 'closed', head: `${owner}:${name}`, per_page: 1
                });
                const merged = pr.data.find(p => p.merged_at);
                if (!merged) continue;
                if ((now - new Date(merged.merged_at).getTime()) < olderThan) continue;

                await github.rest.git.deleteRef({ owner, repo, ref: `heads/${name}` });
                core.info(`Deleted ${name}`);
              } catch (e) {
                core.warning(`Skip ${name}: ${e.message}`);
              }
            }
