name: Update Changelog Discussion

on:
  push:
    branches:
      - main

permissions:
  contents: read
  discussions: write

jobs:
  discussion-update:
    name: Publish changelog to discussions
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update changelog discussion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          FROM_SHA: ${{ github.event.before }}
          TO_SHA: ${{ github.sha }}
          DISCUSSION_CATEGORY: Changelog
          DISCUSSION_TITLE: Automated Changelog
        run: python scripts/discussion_update.py

