version: '3.8'

services:
  frontend-agent:
    image: prcybr/pr-cybr-frontend-agent:latest
    container_name: pr-cybr-frontend-agent
    env_file: .env # Load environment variables from .env file
    volumes:
      - ../../:/workspace
    networks:
      - pr-cybr-net
    ports:
      - "8080:80" # Adjust this port as necessary for the Frontend Agent

networks:
  pr-cybr-net:
    driver: bridge
