name: plan
on:
  issue_comment:
    types: [created]
jobs:
  codex:
    if: startsWith(github.event.comment.body, '/plan')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder for plan workflow
        run: echo "Plan workflow triggered"
