name: Secret Scan

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    outputs:
      status:
        description: Overall status of the secret scan job
        value: ${{ jobs.secret_scan.outputs.status }}
      critical_findings:
        description: Count of critical findings detected by the secret scan
        value: ${{ jobs.secret_scan.outputs.critical_findings }}
      total_findings:
        description: Total findings reported by the secret scan
        value: ${{ jobs.secret_scan.outputs.total_findings }}

permissions:
  contents: read
  pull-requests: write

jobs:
  secret_scan:
    name: Run Gitleaks secret scan
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.evaluate.outputs.status }}
      critical_findings: ${{ steps.evaluate.outputs.critical }}
      total_findings: ${{ steps.evaluate.outputs.total }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        with:
          args: detect --source=. --report-format json --report-path gitleaks-report.json --exit-code 1

      - name: Evaluate Gitleaks results
        id: evaluate
        run: |
          python <<'PY'
          import json
          import os

          path = "gitleaks-report.json"
          total = 0
          critical = 0

          if os.path.exists(path) and os.path.getsize(path):
              with open(path, "r", encoding="utf-8") as handle:
                  try:
                      data = json.load(handle)
                  except json.JSONDecodeError:
                      data = []
              if isinstance(data, list):
                  total = len(data)
                  severities = [str(item.get("Severity", "")).lower() for item in data if isinstance(item, dict)]
                  critical = sum(1 for item in severities if item == "critical")
                  if total and not any(severities):
                      critical = total
          status = "success"
          if critical > 0:
              status = "failure"

          github_output = os.environ["GITHUB_OUTPUT"]
          with open(github_output, "a", encoding="utf-8") as handle:
              handle.write(f"total={total}\n")
              handle.write(f"critical={critical}\n")
              handle.write(f"status={status}\n")
          PY

      - name: Write job summary
        run: |
          {
            echo "### Secret Scan"
            echo ""
            if [ "${{ steps.evaluate.outputs.status }}" = "success" ]; then
              echo "✅ No critical secrets detected."
            else
              echo "❌ Critical secrets detected."
            fi
            echo ""
            echo "- Total findings: ${{ steps.evaluate.outputs.total }}"
            echo "- Critical findings: ${{ steps.evaluate.outputs.critical }}"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Comment on PR with summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          STATUS: ${{ steps.evaluate.outputs.status }}
          TOTAL: ${{ steps.evaluate.outputs.total }}
          CRITICAL: ${{ steps.evaluate.outputs.critical }}
        with:
          script: |
            const marker = '<!-- secret-scan-report -->';
            const status = process.env.STATUS;
            const total = process.env.TOTAL;
            const critical = process.env.CRITICAL;
            const statusLine = status === 'success'
              ? '✅ No critical secrets detected.'
              : '❌ Critical secrets detected.';
            const bodyLines = [
              marker,
              '### Secret Scan Report',
              statusLine,
              `- Total findings: ${total}`,
              `- Critical findings: ${critical}`,
              '',
              'View the full report in the workflow run artifacts.'
            ];
            const body = bodyLines.join('\n');

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100,
            });

            const existing = comments.find(comment => comment.body && comment.body.includes(marker));
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }

      - name: Fail on execution errors
        if: steps.gitleaks.outcome == 'failure' && steps.evaluate.outputs.status == 'success'
        run: |
          echo "Gitleaks execution failed."
          exit 1

      - name: Enforce failure on critical findings
        if: steps.evaluate.outputs.status == 'failure'
        run: |
          echo "Critical secrets were detected by Gitleaks."
          exit 1
