name: setup-dry-run

on:
  push:
    branches:
      - codex
      - dev
      - agents
  pull_request:
    branches:
      - main
  workflow_dispatch: # allow manual trigger from GitHub UI

jobs:
  dry-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run setup.py in dry-run mode
        run: |
          if [ -f setup.py ]; then
            python setup.py --dry-run
          else
            echo "❌ setup.py not found"
            exit 1
          fi

      - name: Mark success
        if: success()
        run: echo "✅ Dry run passed successfully."

      - name: Mark failure
        if: failure()
        run: echo "❌ Dry run failed."
