name: Verify Environment Variables
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      REQUIRED_VARS: |
        AGENT_ACTIONS
        AGENT_COLLAB
        DOCKERHUB_TOKEN
        DOCKERHUB_USERNAME
        GLOBAL_DOMAIN
        GLOBAL_ELASTIC_URI
        GLOBAL_GRAFANA_URI
        GLOBAL_KIBANA_URI
        GLOBAL_PROMETHEUS_URI
        GLOBAL_TAILSCALE_AUTHKEY
        GLOBAL_TRAEFIK_ACME_EMAIL
        GLOBAL_TRAEFIK_ENTRYPOINTS
        GLOBAL_ZEROTIER_NETWORK_ID
        NOTION_DISCUSSIONS_ARC_DB_ID
        NOTION_ISSUES_BACKLOG_DB_ID
        NOTION_KNOWLEDGE_FILE_DB_ID
        NOTION_PAGE_ID
        NOTION_PR_BACKLOG_DB_ID
        NOTION_PROJECT_BOARD_BACKLOG_DB_ID
        NOTION_TASK_BACKLOG_DB_ID
        NOTION_TOKEN
        TFC_TOKEN
    steps:
      - name: Check required environment variables
        run: |
          missing=false
          for var in $REQUIRED_VARS; do
            if [ -z "${!var}" ]; then
              echo "\u274c Missing required environment variable: $var"
              missing=true
            else
              echo "\u2705 $var is set"
            fi
          done
          if [ "$missing" = true ]; then
            echo "One or more required environment variables are missing."
            exit 1
          fi
